name: Fly Deploy Catalyst Linebot Adapter

on:
  workflow_dispatch:
    inputs:
      base_version:
        description: 'Version of catalyst-adapter-base to use'
        required: false
        default: 'latest'

env:
  # Set these to your Fly.io organization and preferred region.
  FLY_APP_NAME: mochicake-linebot
  FLY_REGION: nrt
  FLY_ORG: mochicake
  # Base image tag to use for catalyst-adapter-base. Defaults to 'latest' but can be
  # overridden via the workflow_dispatch input above or by setting github.event.inputs.base_version.
  BASE_VERSION: ${{ github.event.inputs.base_version || 'latest' }}

permissions:
  contents: read
  packages: read

jobs:
  deploy_to_fly:
    name: Deploy Linebot Adapter to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group

    steps:
      - name: Checkout branch ${{ github.ref_name }}
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@1.5

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull down image from Orbis GHCR
        run: |
          docker pull ghcr.io/orbisoperations/catalyst-adapter-base:${{ env.BASE_VERSION }}

      - name: Check local docker images
        run: |
          docker image ls && \
          docker image ls ghcr.io/orbisoperations/catalyst-adapter-base:${{ env.BASE_VERSION }}

      - name: Deploy app to Fly.io
        run: |
          flyctl deploy --local-only --app ${{ env.FLY_APP_NAME }} \
            --primary-region ${{ env.FLY_REGION }} \
            --ha=false \
            --build-arg BASE_VERSION=${{ env.BASE_VERSION }} \

        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
